CREATE TABLE Users (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL UNIQUE, role VARCHAR(255) DEFAULT 'user',isWelcomed BIT DEFAULT(0));

ALTER TABLE Users ADD role VARCHAR(255) DEFAULT 'user' NOT NULL;

ALTER TABLE Users 
ALTER COLUMN role VARCHAR(255) NOT NULL;