###Register user
POST http://localhost:5000/user/register
Content-Type: application/json

{
  "user_name": "Mark",
  "user_email": "mark@example.com",
  "user_password": "marko"
}




### Get All Users
GET http://localhost:5000/user/all

Content-Type: application/json


###login
POST http://localhost:5000/user/login
Content-Type: application/json

{
"user_email": "man@example.com",
  "user_password": "securepassword"
  }


